fragment FlashDesignsParts on FlashDesigns {
  __typename
  title
  price
  category
  image
  description
}

fragment OnSkinWorksParts on OnSkinWorks {
  __typename
  title
  category
  image
  description
}

fragment PortfolioParts on Portfolio {
  __typename
  title
  category
  price
  image
  description
}
