//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  import type { TinaMarkdownContent } from 'tinacms/dist/rich-text';
/** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
  /** A rich-text document, renderable by TinaMarkdown */
  RichText: { input: TinaMarkdownContent; output: TinaMarkdownContent; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  flashDesigns: FlashDesigns;
  flashDesignsConnection: FlashDesignsConnection;
  onSkinWorks: OnSkinWorks;
  onSkinWorksConnection: OnSkinWorksConnection;
  portfolio: Portfolio;
  portfolioConnection: PortfolioConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFlashDesignsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFlashDesignsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FlashDesignsFilter>;
};


export type QueryOnSkinWorksArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryOnSkinWorksConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<OnSkinWorksFilter>;
};


export type QueryPortfolioArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPortfolioConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PortfolioFilter>;
};

export type DocumentFilter = {
  flashDesigns?: InputMaybe<FlashDesignsFilter>;
  onSkinWorks?: InputMaybe<OnSkinWorksFilter>;
  portfolio?: InputMaybe<PortfolioFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = FlashDesigns | OnSkinWorks | Portfolio | Folder;

export type FlashDesigns = Node & Document & {
  __typename?: 'FlashDesigns';
  title: Scalars['String']['output'];
  price?: Maybe<Scalars['String']['output']>;
  category?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type FlashDesignsFilter = {
  title?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type FlashDesignsConnectionEdges = {
  __typename?: 'FlashDesignsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FlashDesigns>;
};

export type FlashDesignsConnection = Connection & {
  __typename?: 'FlashDesignsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FlashDesignsConnectionEdges>>>;
};

export type OnSkinWorks = Node & Document & {
  __typename?: 'OnSkinWorks';
  title: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type OnSkinWorksFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type OnSkinWorksConnectionEdges = {
  __typename?: 'OnSkinWorksConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<OnSkinWorks>;
};

export type OnSkinWorksConnection = Connection & {
  __typename?: 'OnSkinWorksConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<OnSkinWorksConnectionEdges>>>;
};

export type Portfolio = Node & Document & {
  __typename?: 'Portfolio';
  title: Scalars['String']['output'];
  category?: Maybe<Scalars['String']['output']>;
  price?: Maybe<Scalars['String']['output']>;
  image?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['RichText']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PortfolioFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  description?: InputMaybe<RichTextFilter>;
};

export type PortfolioConnectionEdges = {
  __typename?: 'PortfolioConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Portfolio>;
};

export type PortfolioConnection = Connection & {
  __typename?: 'PortfolioConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PortfolioConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateFlashDesigns: FlashDesigns;
  createFlashDesigns: FlashDesigns;
  updateOnSkinWorks: OnSkinWorks;
  createOnSkinWorks: OnSkinWorks;
  updatePortfolio: Portfolio;
  createPortfolio: Portfolio;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateFlashDesignsArgs = {
  relativePath: Scalars['String']['input'];
  params: FlashDesignsMutation;
};


export type MutationCreateFlashDesignsArgs = {
  relativePath: Scalars['String']['input'];
  params: FlashDesignsMutation;
};


export type MutationUpdateOnSkinWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: OnSkinWorksMutation;
};


export type MutationCreateOnSkinWorksArgs = {
  relativePath: Scalars['String']['input'];
  params: OnSkinWorksMutation;
};


export type MutationUpdatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};


export type MutationCreatePortfolioArgs = {
  relativePath: Scalars['String']['input'];
  params: PortfolioMutation;
};

export type DocumentUpdateMutation = {
  flashDesigns?: InputMaybe<FlashDesignsMutation>;
  onSkinWorks?: InputMaybe<OnSkinWorksMutation>;
  portfolio?: InputMaybe<PortfolioMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  flashDesigns?: InputMaybe<FlashDesignsMutation>;
  onSkinWorks?: InputMaybe<OnSkinWorksMutation>;
  portfolio?: InputMaybe<PortfolioMutation>;
};

export type FlashDesignsMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['RichText']['input']>;
};

export type OnSkinWorksMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['RichText']['input']>;
};

export type PortfolioMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['RichText']['input']>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type ImageFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type RichTextFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
};

export type FlashDesignsFilter = {
  title?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  description?: RichTextFilter | null | undefined;
};

export type OnSkinWorksFilter = {
  title?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  description?: RichTextFilter | null | undefined;
};

export type PortfolioFilter = {
  title?: StringFilter | null | undefined;
  category?: StringFilter | null | undefined;
  price?: StringFilter | null | undefined;
  image?: ImageFilter | null | undefined;
  description?: RichTextFilter | null | undefined;
};

export type FlashDesignsPartsFragment = { __typename: 'FlashDesigns', title: string, price: string | null, category: string | null, image: string | null, description: TinaMarkdownContent | null };

export type OnSkinWorksPartsFragment = { __typename: 'OnSkinWorks', title: string, category: string | null, image: string | null, description: TinaMarkdownContent | null };

export type PortfolioPartsFragment = { __typename: 'Portfolio', title: string, category: string | null, price: string | null, image: string | null, description: TinaMarkdownContent | null };

export type FlashDesignsQueryVariables = Exact<{
  relativePath: string;
}>;


export type FlashDesignsQuery = { flashDesigns: { __typename: 'FlashDesigns', id: string, title: string, price: string | null, category: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FlashDesignsConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: FlashDesignsFilter | null | undefined;
}>;


export type FlashDesignsConnectionQuery = { flashDesignsConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'FlashDesigns', id: string, title: string, price: string | null, category: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type OnSkinWorksQueryVariables = Exact<{
  relativePath: string;
}>;


export type OnSkinWorksQuery = { onSkinWorks: { __typename: 'OnSkinWorks', id: string, title: string, category: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type OnSkinWorksConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: OnSkinWorksFilter | null | undefined;
}>;


export type OnSkinWorksConnectionQuery = { onSkinWorksConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'OnSkinWorks', id: string, title: string, category: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PortfolioQueryVariables = Exact<{
  relativePath: string;
}>;


export type PortfolioQuery = { portfolio: { __typename: 'Portfolio', id: string, title: string, category: string | null, price: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PortfolioConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: PortfolioFilter | null | undefined;
}>;


export type PortfolioConnectionQuery = { portfolioConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Portfolio', id: string, title: string, category: string | null, price: string | null, image: string | null, description: TinaMarkdownContent | null, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const FlashDesignsPartsFragmentDoc = gql`
    fragment FlashDesignsParts on FlashDesigns {
  __typename
  title
  price
  category
  image
  description
}
    `;
export const OnSkinWorksPartsFragmentDoc = gql`
    fragment OnSkinWorksParts on OnSkinWorks {
  __typename
  title
  category
  image
  description
}
    `;
export const PortfolioPartsFragmentDoc = gql`
    fragment PortfolioParts on Portfolio {
  __typename
  title
  category
  price
  image
  description
}
    `;
export const FlashDesignsDocument = gql`
    query flashDesigns($relativePath: String!) {
  flashDesigns(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FlashDesignsParts
  }
}
    ${FlashDesignsPartsFragmentDoc}`;
export const FlashDesignsConnectionDocument = gql`
    query flashDesignsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FlashDesignsFilter) {
  flashDesignsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FlashDesignsParts
      }
    }
  }
}
    ${FlashDesignsPartsFragmentDoc}`;
export const OnSkinWorksDocument = gql`
    query onSkinWorks($relativePath: String!) {
  onSkinWorks(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...OnSkinWorksParts
  }
}
    ${OnSkinWorksPartsFragmentDoc}`;
export const OnSkinWorksConnectionDocument = gql`
    query onSkinWorksConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: OnSkinWorksFilter) {
  onSkinWorksConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...OnSkinWorksParts
      }
    }
  }
}
    ${OnSkinWorksPartsFragmentDoc}`;
export const PortfolioDocument = gql`
    query portfolio($relativePath: String!) {
  portfolio(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PortfolioParts
  }
}
    ${PortfolioPartsFragmentDoc}`;
export const PortfolioConnectionDocument = gql`
    query portfolioConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PortfolioFilter) {
  portfolioConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PortfolioParts
      }
    }
  }
}
    ${PortfolioPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      flashDesigns(variables: FlashDesignsQueryVariables, options?: C): Promise<{data: FlashDesignsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FlashDesignsQueryVariables, query: string}> {
        return requester<{data: FlashDesignsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FlashDesignsQueryVariables, query: string}, FlashDesignsQueryVariables>(FlashDesignsDocument, variables, options);
      },
    flashDesignsConnection(variables?: FlashDesignsConnectionQueryVariables, options?: C): Promise<{data: FlashDesignsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FlashDesignsConnectionQueryVariables, query: string}> {
        return requester<{data: FlashDesignsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FlashDesignsConnectionQueryVariables, query: string}, FlashDesignsConnectionQueryVariables>(FlashDesignsConnectionDocument, variables, options);
      },
    onSkinWorks(variables: OnSkinWorksQueryVariables, options?: C): Promise<{data: OnSkinWorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OnSkinWorksQueryVariables, query: string}> {
        return requester<{data: OnSkinWorksQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OnSkinWorksQueryVariables, query: string}, OnSkinWorksQueryVariables>(OnSkinWorksDocument, variables, options);
      },
    onSkinWorksConnection(variables?: OnSkinWorksConnectionQueryVariables, options?: C): Promise<{data: OnSkinWorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OnSkinWorksConnectionQueryVariables, query: string}> {
        return requester<{data: OnSkinWorksConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: OnSkinWorksConnectionQueryVariables, query: string}, OnSkinWorksConnectionQueryVariables>(OnSkinWorksConnectionDocument, variables, options);
      },
    portfolio(variables: PortfolioQueryVariables, options?: C): Promise<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}> {
        return requester<{data: PortfolioQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioQueryVariables, query: string}, PortfolioQueryVariables>(PortfolioDocument, variables, options);
      },
    portfolioConnection(variables?: PortfolioConnectionQueryVariables, options?: C): Promise<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}> {
        return requester<{data: PortfolioConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PortfolioConnectionQueryVariables, query: string}, PortfolioConnectionQueryVariables>(PortfolioConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  