'use client'

import { useState } from 'react'
import { ArrowUpRight, Camera, ChevronDown, MapPin, Menu, MessageCircle, Music2, Sparkles, X } from 'lucide-react'

const instagram = 'https://www.instagram.com/kisu.tatts/'
const tiktok = 'https://www.tiktok.com/@kisu.tatts'

const portfolio = [
  ['Flora', 'kasvit / herkkä', 'art-flora'], ['B&W', 'muste / varjostus', 'art-bw'], ['Color', 'söpö / kirkas', 'art-color'],
  ['Healed', 'parantunut muste', 'art-healed'], ['ALT', 'oudot pienet jutut', 'art-alt'], ['Custom', 'tehty sinulle', 'art-custom'],
]

const translations = {
  en: {
    nav: ['About me', 'Portfolio', 'Flash & pricing', 'Get in touch'], eyebrow: 'Tattoo artist in Tampere', intro: 'Colours, lines & shadows.', book: 'Book now', about: 'About me', portfolio: 'Portfolio', pricing: 'Flash & pricing', booking: 'Booking', faq: 'FAQ', contact: 'Get in touch',
    quote: 'Making tiny pieces of joy\nto live on your skin.', studio: 'est. 2023 / hari.gallery', aboutLead: 'I\'m really friendly and I love to brighten people\'s day ♡ I fell in love with tattoos because they bring joy to both me and others. I adore that my own drawings can live forever on someone\'s skin ✦', aboutText: 'Hi! I\'m Eva :D I\'m really friendly and I love to brighten people\'s day. ♡ I fell in love with tattoos because they bring joy to both me and others. I adore that my own drawings can live forever on someone\'s skin... I\'ve got plenty of ready-to-go designs you can book or we can craft a custom piece exactly the way you want!',
    portfolioTitle: 'Little pieces\nof magic.', portfolioNote: 'Every piece is drawn with a lot of care.\nMore work on Instagram ↗', viewAll: 'view all on Instagram', priceTitle: 'Pick a flash.\nMake it yours.', priceIntro: 'Ready-to-go designs, made with love and a little bit of weird. Choose a price point or message me for a custom idea.', priceNote: 'All flash designs can be booked. Custom designs are always welcome — final price depends on size and detail.',
    bookingTitle: 'Let\'s make\nsomething cute.', bookingIntro: 'Choose a flash design or bring your own idea. We\'ll make it feel like you.', dm: 'DM me on Instagram ♡', address: 'Aspinniemenkatu 5, Tampere', map: 'open map ↗', steps: [['Send a DM', 'Tell me your idea, placement and size.'], ['Talk it through', 'We find the right design and a time that works.'], ['Deposit', 'A small deposit secures your appointment.'], ['Tattoo day', 'Come to Hari Gallery and let the magic happen.']],
    faqTitle: 'Good to\nknow.', questions: [['How do I take care of my new tattoo?', 'I’ll send you clear aftercare instructions after your session. In short: keep it clean, moisturised and out of the sun while it heals.'], ['What languages do you speak?', 'Fin / Eng / Rus — everyone is welcome.'], ['Can I bring my own idea?', 'Absolutely! I love custom work. Send me your references, mood and wishes in a DM.']], contactText: 'Have a question, an idea, or just want to say hello? My DMs are open.', studioLabel: 'Studio', placeholder: 'Portfolio placeholder — add Eva\'s original work here', switchLabel: 'Language switcher', menuLabel: 'Toggle menu', close: 'Close', studioMoments: 'real studio moments\ncoming soon', nice: 'nice to meet you', signature: 'Eva ♡', flash: [['Small & simple', 'stars · octopus · pretzels · puzzles'], ['Cute little ones', 'stars · ghosts · bunnies'], ['Medium', 'wolves · fairies · owls · mushrooms'], ['Medium +', 'rays · hooded cats · clocks · flowers'], ['Large', 'jellyfish · sword rats · twins'], ['Large +', 'Gengar · witch cats · pigeons · Minecraft · Eevee'], ['Detailed', 'bunnies · alien bears · squids · candles · hedgehogs'], ['Large detailed', 'brushes · fish · deer · clown cats · spiders'], ['Very detailed', 'mice · scissors · bugs · branches · skeletons'], ['Maximum detail', 'lizard skeletons · spiky hearts · swords']], footer: '© 2024 Eva / made with care in Tampere',
  },
  fi: {
    nav: ['Minusta', 'Portfolio', 'Flash & hinnat', 'Yhteys'], eyebrow: 'Tatuointitaiteilija Tampereella', intro: 'Värit, linjat & varjot.', book: 'Varaa aika', about: 'Minusta', portfolio: 'Portfolio', pricing: 'Flash & hinnat', booking: 'Varaa aika', faq: 'Usein kysytyt', contact: 'Yhteys',
    quote: 'Pieniä ilon palasia\nelämään ja iholle.', studio: 'vuodesta 2023 / hari.gallery', aboutLead: 'Moikka! Oon Eva <3 Olen todella ystävällinen ja rakastan ilahduttaa muita. Ihastuin tatuointeihin, sillä ne tuovat iloa sekä minulle että muille... Mulla on paljon vapaita malleja, joista voi varata omansa - tai voidaan tehdä custom-tatska just sun toiveiden mukaan!', aboutText: 'Moikka! Oon Eva <3 Olen todella ystävällinen ja rakastan ilahduttaa muita. Ihastuin tatuointeihin, sillä ne tuovat iloa sekä minulle että muille. Rakastan ajatusta siitä, että omat piirrokseni voivat elää ikuisesti jonkun iholla... Mulla on paljon vapaita malleja, joista voi varata omansa - tai voidaan tehdä custom-tatska just sun toiveiden mukaan!',
    portfolioTitle: 'Pieniä palasia\ntaikaa.', portfolioNote: 'Jokainen työ on piirretty suurella huolella.\nLisää töitä Instagramissa ↗', viewAll: 'katso kaikki Instagramissa', priceTitle: 'Valitse flash.\nTee siitä omasi.', priceIntro: 'Valmiita malleja, tehty rakkaudella ja pienellä ripauksella outoutta. Valitse hintaluokka tai lähetä viesti custom-ideasta.', priceNote: 'Kaikki flash-mallit voi varata. Custom-ideat ovat tervetulleita — lopullinen hinta riippuu koosta ja yksityiskohdista.',
    bookingTitle: 'Tehdään jotain\nsöpöä.', bookingIntro: 'Valitse valmis flash-malli tai tuo oma ideasi. Tehdään siitä sinun näköisesi.', dm: 'Lähetä DM Instagramissa ♡', address: 'Aspinniemenkatu 5, Tampere', map: 'avaa kartta ↗', steps: [['Lähetä DM', 'Kerro ideasi, paikka ja koko.'], ['Keskustellaan ideasta', 'Etsitään sopiva malli ja aika.'], ['Maksa varausmaksu', 'Pieni varausmaksu vahvistaa ajan.'], ['Tatuointipäivä', 'Tervetuloa Hari Galleryyn — taika alkaa!']],
    faqTitle: 'Hyvä tietää.', questions: [['Miten hoidan uutta tatuointia?', 'Saat selkeät hoito-ohjeet session jälkeen. Lyhyesti: pidä tatuointi puhtaana ja kosteutettuna sekä poissa auringosta paranemisen ajan.'], ['Mitä kieliä puhut?', 'Fin / Eng / Rus — kaikki ovat tervetulleita.'], ['Voinko tuoda oman ideani?', 'Totta kai! Rakastan custom-töitä. Lähetä referenssit, tunnelma ja toiveet DM:llä.']], contactText: 'Onko sinulla kysymys, idea tai haluatko vain moikata? DM:ni ovat avoinna.', studioLabel: 'Studio', placeholder: 'Portfolion paikka — lisää Evan omat työt tähän', switchLabel: 'Kielen vaihto', menuLabel: 'Avaa valikko', close: 'Sulje', studioMoments: 'oikeita studiokuvia\ntulossa pian', nice: 'kiva tutustua', signature: 'Eva ♡', flash: [['Pienet ja yksinkertaiset', 'tähdet · mustekalat · pretzelit · palapelit'], ['Söpöt pienet', 'tähdet · kummitukset · puput'], ['Keskikokoiset', 'sudet · keijut · pöllöt · sienet'], ['Keskikokoiset +', 'rauskuja · hupparikissoja · kelloja · kukkia'], ['Suuret', 'meduusat · miekkarotat · kaksoset'], ['Suuret +', 'Gengar · noitakissat · kyyhkyt · Minecraft · Eevee'], ['Yksityiskohtaiset', 'puput · avaruuskarhut · kalmarit · kynttilät · siilit'], ['Suuret ja yksityiskohtaiset', 'siveltimet · kalat · peurat · klovni-kissat · hämähäkit'], ['Erittäin yksityiskohtaiset', 'hiiret · sakset · ötökät · oksat · luurangot'], ['Vaativimmat', 'liskoluurangot · piikkisydämet · miekat']], footer: '© 2024 Eva / tehty rakkaudella Tampereella',
  },
} as const

const prices = ['75€', '80€', '90€', '100€', '110€', '120€', '130€', '140€', '160€', '170–180€']

export default function Page() {
  const [lang, setLang] = useState<'en' | 'fi'>('en'); const [menuOpen, setMenuOpen] = useState(false); const [activeArt, setActiveArt] = useState<number | null>(null); const [openFaq, setOpenFaq] = useState<number | null>(0); const c = translations[lang]
  return <main className="site-shell" id="top">
    <header className="topbar"><a href="#top" className="brand" aria-label="kisu.tatts home"><span>kisu</span><i>.tatts</i></a><nav className={menuOpen ? 'nav-links open' : 'nav-links'}>{c.nav.map((item, i) => <a key={item} href={['#about','#portfolio','#pricing','#contact'][i]} onClick={() => setMenuOpen(false)}>{item}</a>)}</nav><div className="header-actions"><div className="lang-switch" aria-label={c.switchLabel}><button className={lang === 'fi' ? 'active' : ''} onClick={() => setLang('fi')}>FI</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')}>EN</button></div><button className="menu-button" aria-label={c.menuLabel} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></div></header>
    <section className="hero"><div className="hero-copy"><p className="kicker"><Sparkles size={14}/> {c.eyebrow}</p><h1>Eva<span className="dot">.</span></h1><p className="hero-lead">{c.intro}<br/><em>Fin / Eng / Rus</em></p><a className="primary-button" href={instagram} target="_blank" rel="noreferrer">{c.book} <ArrowUpRight size={16}/></a></div><div className="avatar-card" aria-label="Pixel art portrait of Eva"><div className="pixel-grid"/><div className="avatar-face"><span className="ear left"/><span className="ear right"/><span className="hair"/><span className="eye one"/><span className="eye two"/><span className="mouth"/><span className="neck"/></div><span className="sticker sticker-one">♡</span><span className="sticker sticker-two">✳</span><p>tampere, finland</p></div><div className="scroll-note">scroll to explore <span>↓</span></div></section>
    <section className="intro-strip"><p>{c.quote.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</p><span>{c.studio}</span></section>
    <section className="section about-section" id="about"><div className="section-label"><span className="section-icon">♡</span> 01 / {c.about}</div><div className="about-grid"><div className="about-photo"><div className="desk-doodle">♡<br/><small>work in progress</small></div><span>{c.studioMoments}</span></div><div className="about-text"><p className="small-heading">{c.nice} <span>♡</span></p><h2>{lang === 'fi' ? 'Moikka, olen Eva!' : "Hi, I'm Eva!"}</h2><p className="body-copy">{c.aboutText}</p><p className="body-copy finnish">{c.aboutLead}</p><p className="signature">{c.signature}</p></div></div></section>
    <section className="section portfolio-section" id="portfolio"><div className="section-head"><div><div className="section-label"><span className="section-icon">✦</span> 02 / {c.portfolio}</div><h2>{c.portfolioTitle.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</h2></div><p>{c.portfolioNote.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</p></div><div className="portfolio-grid">{portfolio.map(([title, tag, className], i) => <button className={`portfolio-card ${className}`} key={title} onClick={() => setActiveArt(i)}><span className="art-shape"/><span className="art-label"><b>{title}</b><small>{lang === 'fi' ? tag : ['botanical / soft','ink / shading','sweet / bright','lived-in ink','odd little things','made for you'][i]}</small></span><span className="view-icon">↗</span></button>)}</div><a className="text-link" href={instagram} target="_blank" rel="noreferrer">{c.viewAll} <ArrowUpRight size={15}/></a></section>
    <section className="price-band" id="pricing"><div className="section price-section"><div className="section-label"><span className="section-icon">🍄</span> 03 / {c.pricing}</div><div className="price-intro"><h2>{c.priceTitle.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</h2><p>{c.priceIntro}</p></div><div className="price-list">{prices.map((price, i) => <div className="price-row" key={price}><strong>{price}</strong><div><b>{c.flash[i][0]}</b><span>{c.flash[i][1]}</span></div><span className="plus">+</span></div>)}</div><p className="price-note">{c.priceNote}</p></div></section>
    <section className="section booking-section" id="booking"><div className="section-label"><span className="section-icon">🐾</span> 04 / {c.booking}</div><div className="booking-grid"><div><h2>{c.bookingTitle.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</h2><p className="body-copy">{c.bookingIntro}</p><a className="primary-button pixel-cta" href={instagram} target="_blank" rel="noreferrer"><MessageCircle size={16}/> {c.dm}</a></div><div className="steps">{c.steps.map(([title, text], i) => <div className="step" key={title}><span>{String(i + 1).padStart(2, '0')}</span><div><b>{title}</b><p>{text}</p></div></div>)}</div></div><div className="address-chip"><MapPin size={16}/><span>{c.address}</span><a href="https://maps.google.com/?q=Aspinniemenkatu+5+Tampere" target="_blank" rel="noreferrer">{c.map}</a></div></section>
    <section className="section faq-section" id="faq"><div className="section-label">05 / {c.faq}</div><div className="faq-layout"><h2>{c.faqTitle.split('\n').map((line) => <span key={line}>{line}<br/></span>)}</h2><div className="faq-list">{c.questions.map(([q, a], i) => <div className={`faq-item ${openFaq === i ? 'open' : ''}`} key={q}><button onClick={() => setOpenFaq(openFaq === i ? null : i)}><span>{q}</span><ChevronDown size={18}/></button>{openFaq === i && <p>{a}</p>}</div>)}</div></div></section>
    <section className="contact-section" id="contact"><div className="section contact-inner"><div><div className="section-label">06 / {c.contact}</div><h2>Say hi<span>.</span></h2><p>{c.contactText}</p><a className="primary-button light" href={instagram} target="_blank" rel="noreferrer">@kisu.tatts <ArrowUpRight size={16}/></a></div><div className="contact-links"><a href={instagram} target="_blank" rel="noreferrer"><Camera size={20}/> Instagram <span>@kisu.tatts</span></a><a href={tiktok} target="_blank" rel="noreferrer"><Music2 size={20}/> TikTok <span>@kisu.tatts</span></a><a href={instagram} target="_blank" rel="noreferrer"><Sparkles size={20}/> {c.studioLabel} <span>@hari.gallery</span></a></div></div><div className="map-frame"><iframe title="Map to Hari Gallery" src="https://www.google.com/maps?q=Aspinniemenkatu%205,%20Tampere&output=embed" loading="lazy"/></div></section>
    <footer><a href="#top" className="brand">kisu<i>.tatts</i></a><span>{c.footer}</span><div><a href={instagram} target="_blank" rel="noreferrer">IG</a><a href={tiktok} target="_blank" rel="noreferrer">TT</a></div></footer>
    {activeArt !== null && <div className="lightbox" role="dialog" aria-modal="true" onClick={() => setActiveArt(null)}><button aria-label={c.close} onClick={() => setActiveArt(null)}><X/></button><div className={`lightbox-art ${portfolio[activeArt][2]}`} onClick={(e) => e.stopPropagation()}><span className="art-shape"/><b>{portfolio[activeArt][0]}</b><small>{c.placeholder}</small></div></div>}
  </main>
}
